apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    app: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: nginxs
        image: nginx
        ports:
        - containerPort: 80
